# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 215342f87b107c31ac08d65e470d88b860a4c3a9f3da72b9016380c9317a8e3d391af4a9a93af9778ac66aee1a74379510f20019cfcf21a83a332b7647e3b5c2

test:
  secret_key_base: 1d4e1b24d3042df5368d2ec21e241bda1f46cda88dd3b27db0836f0300c84cb1ca7384b7a1d30d62858ff6b528d0383e32f4f3862ebc59a0905239f04c64a634

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
